---

- name: Set up a local isolated vm for rccn development
  hosts: rccn
  become: yes

  tasks:
    # Create the rhizomatica group and user, which otherwise are
    # created as part of the debian install workflow.
    - name: Create the rhizomatica group
      group:
        name: rhizomatica

    - name: Create the rhizomatica user
      user:
        name: rhizomatica
        group: rhizomatica
        uid: 2000

   - name: Install utilities for terminal interaction
     apt:
       pkg: ['ccze', 'tmux', 'python3-dev', 'emacs-nox', 'usbutils']
       state: present
       update_cache: yes
       cache_valid_time: 600

    - name: Install puppet
      apt:
        pkg: ['puppet', 'puppetmaster']
        state: present
        update_cache: yes
        cache_valid_time: 600

    - name: Create puppet environments directory
      file:
        path: /etc/puppet/code/environments
        state: directory

    # Link the puppet directories to the mounted development
    # directories from the host instead of cloning directly as is done
    # in the rhizomatica/puppet readme.
    - name: Symlink the production directory to local puppet repo
      file:
        path: "/etc/puppet/code/environments/production"
        src: "/home/vagrant/sources/puppet"
        state: link

    - name: Symlink the hiera directory to local puppet repo
      file:
        path: "/etc/puppet/code/hiera"
        src: "/home/vagrant/sources/puppet/hieradata"
        state: link

    - name: Symlink the top level hiera file to the local puppet repo, overwriting the default.
      file:
        path: "/etc/puppet/hiera.yaml"
        src: "/home/vagrant/sources/puppet/hiera.yaml"
        state: link
        force: yes

    - name: Create the localized puppet config file
      copy:
        src: "/etc/puppet/code/hiera/site_template.yaml"
        dest: "/etc/puppet/code/hiera/{{ ansible_nodename }}.yaml"
        follow: yes
        remote_src: yes

    - name: Add puppet host
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 puppet"
        state: present

    - name: Restart puppetmaster
      service:
        name: puppetmaster
        state: restarted

    - name: Remove old puppet state directory
      file:
        path: "/var/lib/puppet/state"
        state: absent

    # Execute the rhizomatica automated install scripts.
    - name: Run puppet install once
      command: puppet agent --test --ignoreschedules
      # Ignore errors about the missing audio repos
      ignore_errors: true

    - name: Run install configuration script
      command: python ./install.py -f
      args:
        chdir: /var/rhizomatica/rccn

    - name: Reboot machine after install
      reboot:
        reboot_timeout: 60
